/* eslint-disable react/no-unescaped-entities */
import Layout from "@/components/headerMAin/layout";
import HeroSectionPages from "@/components/pagesComp/HeroSection/heroSection";
import SatisfiedNewuser from "@/components/satisfiedusernew/satisfiedNewuser";
import { SatisFiedData } from "@/data/satisfiedData";

import { HeroData } from "@/data/termsCdata";
import { HiOutlineArrowCircleRight } from "react-icons/hi";

const TC = () => {
  return (
    <>
      <Layout>
        <HeroSectionPages items={HeroData} />
        <SatisfiedNewuser items={SatisFiedData} />
        <section className="lg:px-20  overflow-x-hidden  lg:py-12 md:p-12 p-12 max-sm:p-4">
          <div className="container mx-auto">
            <div className="flex flex-wrap">
              <div className="w-full">
                <div>
                  <h2 className="mb-4">TERMS & CONDITIONS</h2>
                  <span className="">Welcome to estivasoftech.com!</span>
                  <p className="text-[16px] mt-4 mb-5">
                    This document is an electronic record in terms of the
                    Information Technology Act, 2000 and rules there under as
                    applicable and the amended provisions about electronic
                    records in various statutes as amended by the Information
                    Technology Act, 2000. This electronic record is generated by
                    a computer system and does not require any physical or
                    digital signatures.
                  </p>
                  <p className="text-[16px] mb-5">
                    These terms and conditions outline the rules and regulations
                    for the use of Estivasoftech's Website, located at
                    https://www.estivasoftech.com.
                  </p>
                  <p className="text-[16px] mb-4">
                    By accessing this Website, we assume you accept these terms
                    and conditions. Do not continue to use estivasoftech.com if
                    you do not agree to take all of the terms and conditions
                    stated on this page.
                  </p>
                  <span className="text-[20px] font-semibold">
                    You must not:-
                  </span>

                  <ul className="mt-4 ">
                    <div className="flex gap-4 mb-4">
                      <i>
                        <HiOutlineArrowCircleRight />
                      </i>
                      <li> Republish material from estivasoftech.com</li>
                    </div>
                    <div className="flex gap-4 mb-4">
                      <i>
                        <HiOutlineArrowCircleRight />
                      </i>
                      <li>
                        Sell, rent, or sub-license material from
                        estivasoftech.com.
                      </li>
                    </div>
                    <div className="flex gap-4 mb-4">
                      <i>
                        <HiOutlineArrowCircleRight />
                      </i>
                      <li>
                        Reproduce, duplicate or copy material from
                        estivasoftech.com
                      </li>
                    </div>
                    <div className="flex gap-4 mb-4">
                      <i>
                        <HiOutlineArrowCircleRight />
                      </i>
                      <li>Redistribute content from estivasoftech.com</li>
                    </div>
                    <div className="flex gap-4 mb-4">
                      <i>
                        <HiOutlineArrowCircleRight />
                      </i>
                      <li>Cookies</li>
                    </div>
                  </ul>

                  <p className="mb-3">
                    We employ the use of cookies. By accessing
                    estivasoftech.com, you agreed to use cookies in the
                    Agreement with Estivasoftech's Privacy Policy.
                  </p>
                  <p>
                    Most interactive websites use cookies to let us retrieve the
                    user's details for each visit. Our Website uses cookies to
                    enable the functionality of certain areas to make it easier
                    for people visiting our Website. Some of our
                    affiliate/advertising partners may also use cookies.
                  </p>

                  <h3 className="mt-4 mb-4 ">
                    MATTER OF DISPUTES AND JURISDICTIONAL ASPECTS :
                  </h3>

                  <p>
                    Any legal disagreement or argument related to HPR
                    ESTIVASOFTECH would be dealt with in Delhi's only territory.
                    All the legal issues are subjected only to applicable
                    contemporary's laws in force at New Delhi to the
                    jurisdiction of courts located in New Delhi only.
                  </p>

                  <h3 className="mt-4 mb-4">
                    GOVERNING LAW AND JURISDICTION :
                  </h3>
                  <p>
                    India's laws govern this Agreement and any dispute or matter
                    arising from incidental use of HPR ESTIVASOFTECH. As a
                    result of this, the Member and the Company submit to the
                    jurisdiction of the courts at Delhi, India. This Agreement,
                    accepted upon use of the Site and further affirmed by
                    becoming a Member of the HPR ESTIVASOFECH., contains the
                    entire Agreement between you and HPR ESTIVASOFECH regarding
                    the use of the Site and the Service. If any provision of
                    this Agreement is held invalid, the remainder of this
                    Agreement shall continue in full force and effect. We
                    anticipate that the information mentioned above would enable
                    you to shrewdly use the facilities and services offered by
                    HPR ESTIVASOFTECH. and strengthen our business associations
                    as well. With the warmest greetings, Team HPR
                    ESTIVASOFTECH.. is all set to assist you in serving with the
                    best possible solutions.
                  </p>
                  <p className="mt-3 mb-4">
                    Payment time duration will start after the Company receive
                    the first payment by the Client. We accept cash as well as a
                    card or digital transaction.
                  </p>
                  <p className="mb-4">
                    The Company shall complete the development of the Portal
                    according to the milestones described in the requirement.
                    Following such milestones, the final product shall be
                    delivered to the Client by [FINAL DELIVERY DATE].
                  </p>

                  <p className="mb-4">
                    Estivasoftech is not responsible for the Client copy write
                    contents to the Client's Site. The Client will be charged an
                    additional amount for re-constructing Development and Yearly
                    Support, based on per year. There is no legal interference
                    of the Company in such cases.
                  </p>

                  <p className="mb-2">
                    *If the Client wants some services that are not mentioned or
                    discussed between both the companies(Additional Services),
                    the Client has to pay more or an additional amount for such
                    service.
                  </p>
                  <p className="mb-2">
                    *The Client must acknowledge the following concerning
                    services:All Amounts, services, documents, recommendations,
                    and reports are confidential.
                  </p>
                  <p>
                    *All the Company's samples will not be misused by the Client
                    or disclosed to the third party.
                  </p>

                  <h3 className="mb-3 mt-3">CONTACT & COMMUNICATION</h3>
                  <span className="font-semibold text-[18px]">
                    We are Unique to other
                  </span>
                  <p>
                    Please contact us for any query or comments (including all
                    inquiries unrelated to copyright infringement) regarding
                    this Website on.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
      </Layout>
    </>
  );
};

export default TC;
